### ISSUE TITLE
Bug Report: Unknown zksolc version v1.4.0

### ISSUE THREAD

**Issue by samui68400** [matter-labs/zksync-cli#124]
#### 📝 Description

The documentation for deploying a contract on zkSync with zksync-cli seems to have an error. When following the provided steps, the deployment script attempts to verify the contract using zksolc v1.4.0, but this version is not recognized, resulting in a verification error.

#### 🔄 Reproduction Steps

- Clone the zksync-cli repository.
- Follow the documentation to create and deploy a contract using yarn deploy.
- Observe the error related to unknown zksolc v1.4.0 version during contract verification.

#### 🤔 Expected Behavior

The deployment script should be able to verify the contract using the correct version of zksolc specified in the environment.

#### 😯 Current Behavior

The deployment script attempts to use zksolc v1.4.0 for contract verification, resulting in an "Unknown zksolc version" error.

#### 🖥️ Environment

- **Package version**: @matterlabs/hardhat-zksync-verify version: 1.3.0
Node version: v18.18.2
NPM/Yarn version: 9.8.1 / 1.22.10
Operating System & Version: macOS Big Sur 14.1.1
- **Other relevant environment details**:

#### 📋 Additional Context

The correct version of zksolc should be automatically installed by the zksync-cli during project setup. However, the documentation suggests a manual download of zksolc-macosx-amd64-v1.4.0, which seems to be incorrect.

#### 📎 Log Output

```diff
hello-zksync2 % yarn deploy

yarn run v1.22.10
warning ../package.json: No license field
$ hardhat deploy-zksync --script deploy.ts

Starting deployment process of "Greeter"...
Estimated deployment cost: 0.0000644766 ETH

"Greeter" was successfully deployed:

Contract address: 0x91E669d972529ABa8b29fE5C09701078b2735dfd
Contract source: contracts/Greeter.sol:Greeter
Encoded constructor arguments: 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000094869207468657265210000000000000000000000000000000000000000000000
Requesting contract verification...
Your verification ID is: 3828

Error in plugin @matterlabs/hardhat-zksync-verify: Backend verification error: Unknown zksolc version: v1.4.0
Error in plugin @matterlabs/hardhat-zksync-verify: Backend verification error: Unknown zksolc version: v1.4.0
For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JackHamer09** [comment]
@samui68400 Thanks a lot for that report. The issue should be resolved now.
This is caused due to desync of latest version of compiler and version available in the verification service. We're actively working on improving the system and the processes, to prevent such issues.

**Comment by samui68400** [comment]
You're welcome! I will try again and I'll keep you posted as soon as I have updates. Thank you for the opportunity to contribute to zkSync development!

**Comment by samui68400** [comment]
<img width="1396" alt="Capture d’écran 2024-02-24 à 09 18 30" src="https://github.com/matter-labs/zksync-cli/assets/107585158/a4685d23-d025-42a8-9810-80b4918f870b">

The issue is successfully resolved. Thank you!
