### ISSUE TITLE
`tx.wait` behaves unexpectantly in tests

### ISSUE THREAD

**Issue by spacesailor24** [matter-labs/zksync-cli#127]
#### 📝 Description

There seems to be some sort of delay between a transaction that transfers ETH being included in a block, and the ETH balance of the receiving account being update and queryable via `provider.getBalance` - `tx.wait` doesn't seem to have an affect

#### 🔄 Reproduction Steps

I've created a minimal reproduction repo [here](https://github.com/spacesailor24/zksync-cli-tx-wait-bug-repro)

#### 🤔 Expected Behavior

After doing:

```typescript
const tx = await wallet.sendTransaction({ value: parseEther('1'), to: receiver });
await tx.wait();

console.log(await wallet.provider.getBalance(receiver));
```

The `console.log`ed value should immediately be `1000000000000000000n`

#### 😯 Current Behavior

The immediate `console.log` (and many after) log `0n`, after sometime `getBalance` finally returns the expected incremented balance for the receiver

#### 🖥️ Environment

- **Package version**: `1.5.1`
- **Node version**: `v20.11.1`
- **NPM/Yarn version**: `pnpm 8.15.4`
- **Operating System & Version**: `macOS Sonoma 14.3.1`
- **Other relevant environment details**:

#### 📋 Additional Context

See [reproduction repo](https://github.com/spacesailor24/zksync-cli-tx-wait-bug-repro)

**Comment by spacesailor24** [comment]
Using the cli, I created a new project using ethersv5 and it doesn't seem to be an issue anymore

**Comment by uF4No** [comment]
hey @spacesailor24 
this might be related to the cache that ethers v6 has implemented by default. This has been mentioned across different issues (example [here](https://github.com/matter-labs/era-test-node/issues/217#issuecomment-1981254689). Please try disabling the cache by initialising your provider this way:

```js
const provider = new Provider(url, undefined, {cacheTimeout: -1});
```

**Comment by dutterbutter** [comment]
Closing due to staleness.
