### ISSUE TITLE
[Feature request] Publish beta version with zksync-ethers@5.8.0-beta.5

### ISSUE THREAD

**Issue by 0xVolosnikov** [matter-labs/zksync-cli#138]
#### 📝 Description

Publish the **beta** version in npm with `zksync-ethers@5.8.0-beta.5` until `zksync-ethers@5.8.0` is released. 

Add `approveBaseERC20: true` param for the `senderWallet.deposit` function call:

https://github.com/matter-labs/zksync-cli/blob/dba8f0e63491c5fedf45f22a4cfb47e139c329b7/src/commands/bridge/deposit.ts#L123

#### 🤔 Rationale

The current version uses zksync-ethers@5.7.2 which means it cannot be used with the new Bridgehub architecture. 

#### 📋 Additional Context

In the specified configuration, it is possible to do deposits and withdrawals, including using a custom base token

**Comment by dutterbutter** [comment]
Closing as its using  "zksync-ethers": "5.9.1"
