### ISSUE TITLE
An error occurs when the npx/ yarn hardhat compile command is run  ,Unable to download zksolc, download page cannot be found

### ISSUE THREAD

**Issue by scholar-zhiwei** [matter-labs/zksync-cli#14]
An error occurs when the npx/ yarn hardhat compile command is run  ,Unable to download zksolc, download page cannot be found
![image](https://user-images.githubusercontent.com/100255425/236363655-a2be9ee9-1fdd-445f-b640-731b96f7039e.png)

**Comment by uF4No** [comment]
hey @scholar-zhiwei can you confirm if this is still an issue? Please try updating both zksync-cli and the the project dependencies. In you hardhat.config.ts you should be able to use `version: "latest"` which will download a newer version of the compiler.

**Comment by dutterbutter** [comment]
Closing due to staleness.
