### ISSUE TITLE
zkSync docker node import to metamask is flagged as scam

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/zksync-cli#144]
#### 📝 Description

Provide a clear and concise description of the bug.

#### 🔄 Reproduction Steps

1. Setup a zkSync local node running in docker:

```
npx zksync-cli dev start
```

2. Import the chain to metamask

<img width="296" alt="Screenshot 2024-05-24 at 1 50 50 PM" src="https://github.com/matter-labs/zksync-cli/assets/54278053/e475739e-9a15-4e64-9073-367c70cdbfe2">

3. You'll see this error
4. 
<img width="831" alt="Screenshot 2024-05-24 at 1 51 17 PM" src="https://github.com/matter-labs/zksync-cli/assets/54278053/5028e7ef-7f71-4722-86b8-2f01327a1179">

<img width="348" alt="Screenshot 2024-05-24 at 1 51 47 PM" src="https://github.com/matter-labs/zksync-cli/assets/54278053/6ea8d122-112c-427f-818f-e64bde02bcb2">

#### 🤔 Expected Behavior

I do not expect to see that.

#### 🖥️ Environment

- **Package version**: `npx zksync-cli --version`
1.7.1
- **Node version**: `v20.11.1`
- **NPM/Yarn version**: npm: 10.8.0
- **Operating System & Version**: MacOS Sonoma 14.5 (23F79)

**Comment by dutterbutter** [comment]
This is due to MM not anything we can prevent as it likely due to the local rpc url.
