### ISSUE TITLE
Support array params in `contract read`

### ISSUE THREAD

**Issue by uF4No** [matter-labs/zksync-cli#164]
#### 📝 Description

Support passing arrays as method params using `zksync-cli contract read`.

#### 🤔 Rationale

Currently not supported. Reported here https://github.com/zkSync-Community-Hub/zksync-developers/discussions/646

#### 🖼️ Mockups/Examples

If applicable, provide mockups or examples of how the feature would work.

#### 📋 Additional Context

Currently fails with the following error:

```
$ zksync-cli contract read
? Chain to use zkSync Mainnet
? Contract address 0x8....4
? Contract method to call getPairInfo(address[] path, bool stable) view returns (address tokenA, address tokenB, address pair, uint256 reserveA, 
uint256 reserveB, uint256 fee)
? Provide method arguments:
? [1/2] path (address[]) [0x5...E,0x0...A]
>> Failed to encode provided argument: expected array value (argument="path", 
value="[0x5...E,0x0...A]", code=INVALID_ARGUMENT, version=abi/5.7.0)
```

**Comment by sleepyqadir** [comment]
Hey @uF4No , can you assign this to me, I can work on this

**Comment by itsacoyote** [comment]
Hi @sleepyqadir I've got a fix incoming for this very shortly!
