### ISSUE TITLE
In Memory Node Connection Error

### ISSUE THREAD

**Issue by bxpana** [matter-labs/zksync-cli#179]
#### 📝 Description

When following the [zkSync 101 Guide](https://docs.zksync.io/build/start-coding/zksync-101/hello-zksync) and running npm run deploy:hello-zksync, I encountered a socket hang up error during deployment. Additionally, when checking the balance using cast balance, I received a connection error. Both issues seem related to the network or RPC configuration.

#### 🔄 Reproduction Steps

1. Follow the steps in the zkSync 101 Guide to set up the project.
2. Attempt deployment with the following command: `npm run deploy:hello-zksync`
3. Test cast balance: `cast balance 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --rpc-url http://127.0.0.1:8011`

#### 🤔 Expected Behavior

- The deployment script should deploy the contract without errors.
- The cast balance command should return the balance of the specified address.

#### 😯 Current Behavior

- Deployment fails with a socket hang up error.
- The cast balance command returns a connection error (Connection reset by peer).

#### 🖥️ Environment

nodejs 22.11.0
npm 10.9.0
npx 10.9.0
pnpm 9.14.4

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by bxpana** [comment]
Stems from: https://github.com/zkSync-Community-Hub/zksync-developers/issues/796

**Comment by itegulov** [comment]
Solved in era-test-node release `v0.1.0-alpha.35`
