### ISSUE TITLE
[feature request] Allow setting values from ENV variables and command line flags

### ISSUE THREAD

**Issue by mm-zk** [matter-labs/zksync-cli#34]
Currently you have to 'paste' values (like account_id, keys, amounts) when you're prompted.

This is great if you run the tool once, but when you use it multiple times during development, it becomes very cumbersome.

We should allow people to specify these things via command line flags (or via ENV variables - for things like private keys).

**Comment by JackHamer09** [comment]
Implemented long time ago, so closing this issue :)
