### ISSUE TITLE
Deploy issue 

### ISSUE THREAD

**Issue by Armankhan566** [matter-labs/zksync-cli#37]
Very long time try deploy available fund gas fee but not working

**Comment by dutterbutter** [comment]
@Armankhan566 can you please provide more detail of your issue?

**Comment by Armankhan566** [comment]
zkSync Era deploy not working

My address is 
0x88686F7A5Db76c4462efcc0b7CAE5c4F9A3c15F0

**Comment by JackHamer09** [comment]
Hey, sorry I'll close this issue for now. If you still face issues, create a new issue using template and fill in the details.
Thanks!
