### ISSUE TITLE
Implement Commands to Interact with Accounts and Contracts

### ISSUE THREAD

**Issue by idea404** [matter-labs/zksync-cli#54]
#### 📝 Description

I would find it handy for the CLI to provide a simple syntax for:

  1. sending ETH between accounts for a specified network and
  2. to interact with contract methods on behalf of an account
  3. deploy contract bytecode to an address

#### 🤔 Rationale

I would like to quickly test or send funds without having to open my browser or copy/paste and edit multiple lines of code. 

#### 🖼️ Mockups/Examples

**Sending ETH between accounts**
`PRIVATE_KEY=0x123myprivatekey... zksync-cli send 0.5 0x123... 0xfoo..` -> sends 0.5 ETH from 0x123... to 0xfoo... and signs with provided private key in env var

**Interact with deployed contract methods**
`zksync-cli view "get_value" 0x123... {}` -> calls the `get_value` method of the contract deployed to 0x123... with no parameters (`{}`) 

`PRIVATE_KEY=0x123myprivatekey... zksync-cli call "change_value" 0xfoo... {"value": "new value"}` -> calls the `change_value` method of the contract deployed to 0xfoo... with the `value` specified in the object and the transaction is signed by the `PRIVATE_KEY` env var provided

**Deploy contract bytecode to address**
`PRIVATE_KEY=0x123myprivatekey... zksync-cli deploy ./file_bytecode_path 0x12345adress... {}` -> deploys the `./file_bytecode_path` to 0x12345adress and passes no constructor params as none were specified and signs the transaction with the provided private key env var

**Comment by JackHamer09** [comment]
Most of these commands are now available:

- Sending ETH between accounts: `npx zksync-cli wallet transfer`
- Interact with deployed contract:
  - Read (view): `npx zksync-cli contract read`
  - Write: `npx zksync-cli contract write`
  - Extended documentation and examples available [here](https://github.com/matter-labs/zksync-cli/blob/main/docs/contract-interaction.md)
- Get transaction info (and decode it):
  - `npx zksync-cli transaction info`
  - Extended documentation and examples available [here](https://github.com/matter-labs/zksync-cli/blob/main/docs/transaction-info.md)
