### ISSUE TITLE
Global Dependency Introduced

### ISSUE THREAD

**Issue by idea404** [matter-labs/zksync-cli#57]
#### 📝 Description

`patch package` is required as a global dep in order to use the newest version of zksync-cli. 

#### 🔄 Reproduction Steps

1. See this CI output: https://github.com/matter-labs/tutorials/pull/17

#### 🤔 Expected Behavior

Installation should pass.

#### 😯 Current Behavior

Installation of zksync-cli fails when installing globally. 

<img width="1414" alt="image" src="https://github.com/matter-labs/zksync-cli/assets/10233439/b0521a9b-62c7-4306-a56c-6dff0af8ad56">

**Comment by JackHamer09** [comment]
The problem was cause by `@rudderstack/rudder-sdk-node` package. It was incorrectly included dependency in RudderStack's SDK package.

Issue was resolved in https://github.com/matter-labs/zksync-cli/pull/69
