### ISSUE TITLE
Ledger device: UNKNOWN_ERROR (0x650f)

### ISSUE THREAD

**Issue by 0xluizsantana** [matter-labs/zksync-cli#58]
Trying to swap in SyncSwap and got this error: https://prnt.sc/MNsqYLs0siXr

**Comment by 0xluizsantana** [comment]
Same error trying to collect rewars from Mute: https://prnt.sc/9Km0zbz73VVa

**Comment by 0xluizsantana** [comment]
Noticed Custom Nounce was 0, then i changed to 1 and still got erro on Velocore: https://prnt.sc/xRzStJkcN0Yg

**Comment by dutterbutter** [comment]
Please post detailed questions to [Dev Discussions](https://github.com/zkSync-Community-Hub/zkync-developers/discussions). Closing this as its unrelated to the CLI.
