### ISSUE TITLE
Can I use this CLI repo for other networks?

### ISSUE THREAD

**Issue by zydjohnHotmail** [matter-labs/zksync-cli#6]
Hello:
I found this repo is rather interesting.  I want to know if I can use this repo for other networks, like: Ethereum or test net like Goerli?
To make the repo work for other networks, what kinds of information have to be provided?
Or we can only use this for zksync network?
Please advise,
Thanks,

**Comment by uF4No** [comment]
Yes! You'd need to add any other networks in the `hardhat.config.ts` file with the flag `zksync: false`. 
You can find an example config file for both zkSync and other EVMs [in this section of the docs](https://era.zksync.io/docs/api/hardhat/migrating-to-zksync.html#full-configuration) ✌️
