### ISSUE TITLE
CLI Should Offer More Tools and Configurations

### ISSUE THREAD

**Issue by idea404** [matter-labs/zksync-cli#61]
#### 📝 Description

The CLI should include more tools and configurations to offer developers more flexibility when initiating a project, a proposed set of options would be:

- Contract Development:
  - Hardhat + Solidity
  - Forge + Solidity
  - Hardhat + Vyper
  - Forge + Vyper
- Web dApp (with contract integration, maybe even wallet support):
  - React
  - Next.js
  - Vite
- Mobile:
  - react native
  - ios
- Scripting:
  - node
  - bun

#### 🤔 Rationale

Developers typically place significant emphasis on their intended project setup. For instance, while it's beneficial to provide a starter contract for an NFT project, what truly adds value is how efficiently they can bootstrap their project with their desired tools and configurations. In essence, it's not really about the contracts because they will likely write their own entirely for their specific needs, but it's about how seamlessly they can integrate into a preferred environment quickly.

#### 🖼️ Mockups/Examples

Example commands: 

```sh
zksync-cli create-project demo --tool forge --contract solidity --project hello_world --frontend react
```

#### 📋 Additional Context

As mentioned on #60

**Comment by JackHamer09** [comment]
Just updated with more templates - https://github.com/matter-labs/zksync-cli/pull/76
Find latest info in docs - https://era.zksync.io/docs/tools/zksync-cli/#quick-scaffolding-with-templates
