### ISSUE TITLE
[BUG] `create-project` does not correctly re-init `.git` includes commit history from template repo

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/zksync-cli#62]
#### 📝 Description

When you make use of `create-project` and push to a new repository the commit history of the template repo gets included.

#### 🔄 Reproduction Steps

1. Run: `zksync-cli create-project test`
2. Create a new repo
3. Set url `git remote set-url origin ssh-git-url` 
4. Push to new repo `git push origin main`
5. Observe 40+ commits!!!!

#### 🤔 Expected Behavior

Should initialize an empty repo

#### 😯 Current Behavior

Includes commit history from template repo.

**Comment by JackHamer09** [comment]
Issue was resolved in https://github.com/matter-labs/zksync-cli/pull/67
Not .git folder is properly removed when using `create project` command
