### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by trusch** [matter-labs/zksync-cli#72]
#### 📝 Description

Let's add the option to use podman as Container engine.

#### 🤔 Rationale

By now the new (awesome) dev subcommand is using docker to spin up the dev env. The usage of docker brings some security risks because all containers are started from a process that runs as root. Using podman, which has nearly the same command line interface, would solve this because it can run root-less. It is installable by package managers of all major distributions.

#### 🖼️ Mockups/Examples

`zksync-cli dev start --container-engine podman`

#### 📋 Additional Context

This could also work without any additional comma d line flags just by detecting if podman or docker is installed on the host system. Also the code change should be minimal and only consist of changing "docker" to "podman" in the command line calls

**Comment by JackHamer09** [comment]
Thank you for your suggestion to use Podman as an alternative container engine. While Podman offers notable security benefits, we need to consider its less widespread adoption compared to Docker, which may introduce hidden complexities and compatibility challenges. We appreciate your input and will keep it in mind for future discussions about our development environment.
