### ISSUE TITLE
Small bug: `.env.example` still there after adding private key through wizard

### ISSUE THREAD

**Issue by idea404** [matter-labs/zksync-cli#77]
#### 📝 Description

Provide a clear and concise description of the bug.

#### 🔄 Reproduction Steps

1. Give the wizard a private key and finish scaffolding the project

#### 🤔 Expected Behavior

for there only to be a `.env` file at project root, but instead `.env.example` is also there

#### 😯 Current Behavior

Both files are there

#### 🖥️ Environment

- **Package version**: [e.g., 1.2.1]
- **Node version**: [e.g., node v16.14.0]
- **NPM/Yarn version**: [e.g., npm 8.3.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:

#### 📋 Additional Context

<img width="1026" alt="image" src="https://github.com/matter-labs/zksync-cli/assets/10233439/25d444e4-2717-4d1c-9620-e65d616aa046">

**Comment by JackHamer09** [comment]
@idea404 This is expected, cause if people gonna upload it to their own repos they want to have this example env for others to reuse. What do you think?

**Comment by idea404** [comment]
I see what you mean @JackHamer09. Makes sense to me. Closing this issue
